services:
  - type: web
    name: secure-vote-demo
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix server && cd server && npx prisma generate && npx prisma db push --accept-data-loss && cd .. && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true

